name: "CI"
on:
  push:
    branches:
      - master
      - ci
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build Nix
        id: build-nix
        run: |
          nix run github:srid/nixci
      - name: Run test
        id: test
        run: |
          nix run nixpkgs#bash runtest.sh
